In [46]:
import pandas as pd
df=pd.read_csv("trek_data.csv")
df.head()

,booking_id,customer_email,trek_location,package_duration_days,difficulty_level,booking_date,season,price_per_person,group_size,total_amount,cancellation_status,number_of_people_cancelled,customer_age,customer_city
0,1,user1@gmail.com,Hampta Pass,5,Moderate,26-10-2023,Peak,14400,4,57600,Completed,0,29,Chennai
1,2,user2@gmail.com,Sandakphu,6,Difficult,15-03-2025,Moderate,15000,3,45000,Completed,0,25,Hyderabad
2,3,user3@gmail.com,Kedarkantha,7,Moderate,06-09-2023,Moderate,14000,6,84000,Completed,0,21,Chennai
3,4,user4@gmail.com,Triund,2,Easy,23-02-2024,Peak,4800,2,9600,Completed,0,31,Pune
4,5,user5@gmail.com,Hampi,5,Easy,16-10-2023,Peak,10800,3,32400,Completed,0,44,Pune

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   booking_id                  500 non-null    int64
 1   customer_email              500 non-null    object
 2   trek_location               500 non-null    object
 3   package_duration_days       500 non-null    int64
 4   difficulty_level            500 non-null    object
 5   booking_date                500 non-null    object
 6   season                      500 non-null    object
 7   price_per_person            500 non-null    int64
 8   group_size                  500 non-null    int64
 9   total_amount                500 non-null    int64
 10  cancellation_status         500 non-null    object
 11  number_of_people_cancelled  500 non-null    int64
 12  customer_age                500 non-null    int64
 13  customer_city               500 non-null    object
dtypes: int64(7), object(7)
memory usage: 54.8+ KB

In [48]:
df.describe()

,booking_id,package_duration_days,price_per_person,group_size,total_amount,number_of_people_cancelled,customer_age
count,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000,500.00000
mean,250.500000,5.22800,11767.400000,3.494000,41214.200000,0.464000,36.45600
std,144.481833,1.61903,4345.234097,1.721596,26224.164275,1.311543,10.86223
min,1.000000,2.00000,3400.000000,1.000000,3400.000000,0.000000,18.00000
25%,125.750000,5.00000,9000.000000,2.000000,16950.000000,0.000000,27.00000
50%,250.500000,6.00000,12000.000000,3.000000,36000.000000,0.000000,37.00000
75%,375.250000,6.00000,15000.000000,5.000000,60000.000000,0.000000,46.00000
max,500.000000,7.00000,18000.000000,6.000000,108000.000000,6.000000,55.00000

In [49]:
df.isnull().sum()

booking_id                    0
customer_email                0
trek_location                 0
package_duration_days         0
difficulty_level              0
booking_date                  0
season                        0
price_per_person              0
group_size                    0
total_amount                  0
cancellation_status           0
number_of_people_cancelled    0
customer_age                  0
customer_city                 0
dtype: int64

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
#change datatypes
df["booking_date"] = pd.to_datetime(df["booking_date"])

C:\Users\Prathamesh\AppData\Local\Temp\ipykernel_23172\281262285.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["booking_date"] = pd.to_datetime(df["booking_date"])

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   booking_id                  500 non-null    int64
 1   customer_email              500 non-null    object
 2   trek_location               500 non-null    object
 3   package_duration_days       500 non-null    int64
 4   difficulty_level            500 non-null    object
 5   booking_date                500 non-null    datetime64[ns]
 6   season                      500 non-null    object
 7   price_per_person            500 non-null    int64
 8   group_size                  500 non-null    int64
 9   total_amount                500 non-null    int64
 10  cancellation_status         500 non-null    object
 11  number_of_people_cancelled  500 non-null    int64
 12  customer_age                500 non-null    int64
 13  customer_city               500 non-null    object
dtypes: datetime64[ns](1), int64(7), object(6)
memory usage: 54.8+ KB

In [53]:
#create columns for year and month
df["year"] = df["booking_date"].dt.year
df["month"] = df["booking_date"].dt.month_name()

In [54]:
# age group column
bins = [17, 24, 34, 100]
labels = ["Young Adult", "Adult", "Senior"]

df["age_group"] = pd.cut(
    df["customer_age"],
    bins=bins,
    labels=labels
)

In [55]:
df.head()

,booking_id,customer_email,trek_location,package_duration_days,difficulty_level,booking_date,season,price_per_person,group_size,total_amount,cancellation_status,number_of_people_cancelled,customer_age,customer_city,year,month,age_group
0,1,user1@gmail.com,Hampta Pass,5,Moderate,2023-10-26,Peak,14400,4,57600,Completed,0,29,Chennai,2023,October,Adult
1,2,user2@gmail.com,Sandakphu,6,Difficult,2025-03-15,Moderate,15000,3,45000,Completed,0,25,Hyderabad,2025,March,Adult
2,3,user3@gmail.com,Kedarkantha,7,Moderate,2023-09-06,Moderate,14000,6,84000,Completed,0,21,Chennai,2023,September,Young Adult
3,4,user4@gmail.com,Triund,2,Easy,2024-02-23,Peak,4800,2,9600,Completed,0,31,Pune,2024,February,Adult
4,5,user5@gmail.com,Hampi,5,Easy,2023-10-16,Peak,10800,3,32400,Completed,0,44,Pune,2023,October,Senior

In [56]:
#cancellation rate
cancellation_rate = (
    df["cancellation_status"].str.contains("Cancelled").sum()
    / len(df)
) * 100
print(cancellation_rate)

14.6

In [57]:
#acrtual_revenue
refund_map = {
    "Completed": 1,
    "Partial Cancellation": 0.5,
    "Full Refund": 0
}

df["actual_revenue"] = (
    df["total_amount"] *
    df["cancellation_status"].map(refund_map)
).fillna(0)

In [58]:
df.head()

,booking_id,customer_email,trek_location,package_duration_days,difficulty_level,booking_date,season,price_per_person,group_size,total_amount,cancellation_status,number_of_people_cancelled,customer_age,customer_city,year,month,age_group,actual_revenue
0,1,user1@gmail.com,Hampta Pass,5,Moderate,2023-10-26,Peak,14400,4,57600,Completed,0,29,Chennai,2023,October,Adult,57600.0
1,2,user2@gmail.com,Sandakphu,6,Difficult,2025-03-15,Moderate,15000,3,45000,Completed,0,25,Hyderabad,2025,March,Adult,45000.0
2,3,user3@gmail.com,Kedarkantha,7,Moderate,2023-09-06,Moderate,14000,6,84000,Completed,0,21,Chennai,2023,September,Young Adult,84000.0
3,4,user4@gmail.com,Triund,2,Easy,2024-02-23,Peak,4800,2,9600,Completed,0,31,Pune,2024,February,Adult,9600.0
4,5,user5@gmail.com,Hampi,5,Easy,2023-10-16,Peak,10800,3,32400,Completed,0,44,Pune,2023,October,Senior,32400.0

In [59]:
df["actual_revenue"].mean()

np.float64(36138.2)

In [60]:
#Group-wise Analysis
df.groupby("trek_location")["actual_revenue"].sum().sort_values(ascending=False)

trek_location
Kedarkantha          4993100.0
Sandakphu            4447500.0
Hampta Pass          3093000.0
Valley of Flowers    2287350.0
Hampi                2260350.0
Triund                987800.0
Name: actual_revenue, dtype: float64

In [61]:
#Most prefered trek
df["trek_location"].value_counts()

trek_location
Kedarkantha          106
Sandakphu             92
Hampi                 87
Triund                84
Hampta Pass           69
Valley of Flowers     62
Name: count, dtype: int64

In [62]:
#Cancellation by Season
df.groupby("season")["number_of_people_cancelled"].sum()

season
Moderate    94
Off         69
Peak        69
Name: number_of_people_cancelled, dtype: int64

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   booking_id                  500 non-null    int64
 1   customer_email              500 non-null    object
 2   trek_location               500 non-null    object
 3   package_duration_days       500 non-null    int64
 4   difficulty_level            500 non-null    object
 5   booking_date                500 non-null    datetime64[ns]
 6   season                      500 non-null    object
 7   price_per_person            500 non-null    int64
 8   group_size                  500 non-null    int64
 9   total_amount                500 non-null    int64
 10  cancellation_status         500 non-null    object
 11  number_of_people_cancelled  500 non-null    int64
 12  customer_age                500 non-null    int64
 13  customer_city               500 non-null    object
 14  year                        500 non-null    int32
 15  month                       500 non-null    object
 16  age_group                   500 non-null    category
 17  actual_revenue              500 non-null    float64
dtypes: category(1), datetime64[ns](1), float64(1), int32(1), int64(7), object(7)
memory usage: 65.2+ KB

In [64]:
df.to_csv("trekking_dataset.csv", index=False)

In [65]:
#Connect python to pgadmin for further analysis
import pandas as pd
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
username="postgres"
password="Admin"
host="localhost"
port="5433"
database="Trek_Business_Analysis"

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name="trek"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'trek' in database 'Trek_Business_Analysis'.